// Code generated by mockery v2.40.1. DO NOT EDIT.

package authorizer

import mock "github.com/stretchr/testify/mock"

// MockClaimsVerifier is an autogenerated mock type for the ClaimsVerifier type
type MockClaimsVerifier struct {
	mock.Mock
}

type MockClaimsVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClaimsVerifier) EXPECT() *MockClaimsVerifier_Expecter {
	return &MockClaimsVerifier_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *MockClaimsVerifier) Execute(_a0 []string, _a1 []string) (string, []error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 []error
	if rf, ok := ret.Get(0).(func([]string, []string) (string, []error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func([]string, []string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func([]string, []string) []error); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]error)
		}
	}

	return r0, r1
}

// MockClaimsVerifier_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockClaimsVerifier_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 []string
//   - _a1 []string
func (_e *MockClaimsVerifier_Expecter) Execute(_a0 interface{}, _a1 interface{}) *MockClaimsVerifier_Execute_Call {
	return &MockClaimsVerifier_Execute_Call{Call: _e.mock.On("Execute", _a0, _a1)}
}

func (_c *MockClaimsVerifier_Execute_Call) Run(run func(_a0 []string, _a1 []string)) *MockClaimsVerifier_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string), args[1].([]string))
	})
	return _c
}

func (_c *MockClaimsVerifier_Execute_Call) Return(_a0 string, _a1 []error) *MockClaimsVerifier_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClaimsVerifier_Execute_Call) RunAndReturn(run func([]string, []string) (string, []error)) *MockClaimsVerifier_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClaimsVerifier creates a new instance of MockClaimsVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClaimsVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClaimsVerifier {
	mock := &MockClaimsVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
