// Code generated by mockery v2.40.1. DO NOT EDIT.

package opa_client

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockStreamReaderFn is an autogenerated mock type for the StreamReaderFn type
type MockStreamReaderFn struct {
	mock.Mock
}

type MockStreamReaderFn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStreamReaderFn) EXPECT() *MockStreamReaderFn_Expecter {
	return &MockStreamReaderFn_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockStreamReaderFn) Execute(_a0 io.Reader) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStreamReaderFn_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockStreamReaderFn_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 io.Reader
func (_e *MockStreamReaderFn_Expecter) Execute(_a0 interface{}) *MockStreamReaderFn_Execute_Call {
	return &MockStreamReaderFn_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockStreamReaderFn_Execute_Call) Run(run func(_a0 io.Reader)) *MockStreamReaderFn_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Reader))
	})
	return _c
}

func (_c *MockStreamReaderFn_Execute_Call) Return(_a0 error) *MockStreamReaderFn_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStreamReaderFn_Execute_Call) RunAndReturn(run func(io.Reader) error) *MockStreamReaderFn_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStreamReaderFn creates a new instance of MockStreamReaderFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStreamReaderFn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStreamReaderFn {
	mock := &MockStreamReaderFn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
